### ISSUE TITLE
It can be better

### ISSUE THREAD

**Issue by hostGG** [Ggre55/CapMonster-Checker#1]
Has much errors not very responsive, and i've got Residential proxies doesn't work as expected

**Comment by Ggre55** [comment]
Well do you have any suggestions??
And yes someone already reported that proxies doesn't work it's actually a mistake i made that's causing the errors and when you don't use proxies they rate limiting connections from ur ip thats causing more errors, ill work on fixing it tonight it should be a simple fix, thanks by the way

**Comment by Ggre55** [comment]
Fixed its way better now thank u for ur feedback

**Comment by Ggre55** [comment]
Fixed its way better now thank u for ur feedback
