### ISSUE TITLE
Proxy and key checking issue

### ISSUE THREAD

**Issue by GamingMazen** [Ggre55/CapMonster-Checker#2]
when I try to use with rotating or residental or free proxies it gives a log and don't do anything else
the log:
[WARNING] [2023-08-23 15:17:38,186] - [!] No keys available. Generating new keys…
Do you want to use proxies? (y/n): y
[INFO] [2023-08-23 15:17:40,599] - Validating proxies…
[ERROR] [2023-08-23 15:17:40,600] - Exception in checking key  -> Unknown scheme for proxy URL URL(‘[p.webshare.io:80](http://p.webshare.io/):myuser:mypass)
[INFO] [2023-08-23 15:17:40,601] - [*] Starting checker with 1000 keys…
[ERROR] [2023-08-23 15:17:40,601] - [ERROR] Exception in checker -> list index out of range
what should I do or can you fix it?

**Comment by Ggre55** [comment]
Fixed new version out
